// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/checkpoints": {
            "get": {
                "description": "get all checkpoints",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkpoints"
                ],
                "summary": "List checkpoints",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Checkpoint"
                            }
                        }
                    },
                    "500": {
                        "description": "Unable to retrieve checkpoints"
                    }
                }
            }
        },
        "/checkpoints/cities/{country}": {
            "get": {
                "description": "get all cities for a given country",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkpoints"
                ],
                "summary": "List cities by country",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country",
                        "name": "country",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.City"
                            }
                        }
                    },
                    "404": {
                        "description": "Country not found"
                    }
                }
            }
        },
        "/checkpoints/country/{city}": {
            "get": {
                "description": "get the country for a given city",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkpoints"
                ],
                "summary": "Get country by city",
                "parameters": [
                    {
                        "type": "string",
                        "description": "City",
                        "name": "city",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Country",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "City not found"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Checkpoint": {
            "description": "Represents a checkpoint with a city and a country",
            "type": "object",
            "required": [
                "country",
                "latitude",
                "longitude",
                "name"
            ],
            "properties": {
                "country": {
                    "$ref": "#/definitions/models.Country"
                },
                "id": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "$ref": "#/definitions/models.City"
                }
            }
        },
        "models.City": {
            "description": "Represents a city name within a country",
            "type": "string",
            "enum": [
                "Paris",
                "Marseille",
                "Perpignan",
                "Strasbourg",
                "Lyon",
                "Rome",
                "Florence",
                "Milan",
                "Como",
                "Naples",
                "Geneva",
                "Zurich",
                "Bern",
                "Lausanne",
                "Chatel-Saint-Denis",
                "Madrid",
                "Barcelona",
                "Seville",
                "Lloret del Mar",
                "Malaga",
                "Lisbon",
                "Porto",
                "Braga",
                "Leiria",
                "Evora"
            ],
            "x-enum-varnames": [
                "CityParis",
                "CityMarseille",
                "CityPerpignan",
                "CityStrasbourg",
                "CityLyon",
                "CityRome",
                "CityFlorence",
                "CityMilan",
                "CityComo",
                "CityNaples",
                "CityGeneva",
                "CityZurich",
                "CityBern",
                "CityLausanne",
                "CityChatelSaintDenis",
                "CityMadrid",
                "CityBarcelona",
                "CitySeville",
                "CityLloretDelMar",
                "CityMalaga",
                "CityLisbon",
                "CityPorto",
                "CityBraga",
                "CityLeiria",
                "CityEvora"
            ]
        },
        "models.Country": {
            "description": "Represents a country",
            "type": "string",
            "enum": [
                "France",
                "Italy",
                "Switzerland",
                "Spain",
                "Portugal"
            ],
            "x-enum-varnames": [
                "CountryFrance",
                "CountryItaly",
                "CountrySwitzerland",
                "CountrySpain",
                "CountryPortugal"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
