definitions:
  models.Checkpoint:
    description: Represents a checkpoint with a city and a country
    properties:
      country:
        $ref: '#/definitions/models.Country'
      id:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      name:
        $ref: '#/definitions/models.City'
    required:
    - country
    - latitude
    - longitude
    - name
    type: object
  models.City:
    description: Represents a city name within a country
    enum:
    - Paris
    - Marseille
    - Perpignan
    - Strasbourg
    - Lyon
    - Rome
    - Florence
    - Milan
    - Como
    - Naples
    - Geneva
    - Zurich
    - Bern
    - Lausanne
    - Chatel-Saint-Denis
    - Madrid
    - Barcelona
    - Seville
    - Lloret del Mar
    - Malaga
    - Lisbon
    - Porto
    - Braga
    - Leiria
    - Evora
    type: string
    x-enum-varnames:
    - CityParis
    - CityMarseille
    - CityPerpignan
    - CityStrasbourg
    - CityLyon
    - CityRome
    - CityFlorence
    - CityMilan
    - CityComo
    - CityNaples
    - CityGeneva
    - CityZurich
    - CityBern
    - CityLausanne
    - CityChatelSaintDenis
    - CityMadrid
    - CityBarcelona
    - CitySeville
    - CityLloretDelMar
    - CityMalaga
    - CityLisbon
    - CityPorto
    - CityBraga
    - CityLeiria
    - CityEvora
  models.Country:
    description: Represents a country
    enum:
    - France
    - Italy
    - Switzerland
    - Spain
    - Portugal
    type: string
    x-enum-varnames:
    - CountryFrance
    - CountryItaly
    - CountrySwitzerland
    - CountrySpain
    - CountryPortugal
info:
  contact: {}
paths:
  /checkpoints:
    get:
      consumes:
      - application/json
      description: get all checkpoints
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Checkpoint'
            type: array
        "500":
          description: Unable to retrieve checkpoints
      summary: List checkpoints
      tags:
      - checkpoints
  /checkpoints/cities/{country}:
    get:
      consumes:
      - application/json
      description: get all cities for a given country
      parameters:
      - description: Country
        in: path
        name: country
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.City'
            type: array
        "404":
          description: Country not found
      summary: List cities by country
      tags:
      - checkpoints
  /checkpoints/country/{city}:
    get:
      consumes:
      - application/json
      description: get the country for a given city
      parameters:
      - description: City
        in: path
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Country
          schema:
            type: string
        "404":
          description: City not found
      summary: Get country by city
      tags:
      - checkpoints
swagger: "2.0"
